title: Susan Korwa # your name (or website title) here
logo: "/passports.j.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Summary
  <br>I hold a MSc in Data Analytics. Currently employed as a Data Analyst. Currently using R, Excel, PowerBI , SQL in my day to day work<br>
 
  <br><br>
  <a href="https://www.linkedin.com/in/susan-korwa/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
