title: Susan Korwa | Impact Data Analyst
email: susankorwa7@gmail.com
description: >- 
  Portfolio of Susan Korwa — Impact Systems Officer and MEAL Analyst.
  Experienced in Power BI, R, SQL, Python, ODK, and QGIS.
baseurl: ""
url: "https://korwa.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav:
  - title: "Home"
    url: /
  - title: "Toolbox"
    url: /toolbox/
  - title: "Dashboards"
    url: /projects/
  - title: "Resume"
    url: /resume/
  - title: "Contact"
    url: /contact/
google_analytics: UA-000000-0
