title: Susan Korwa
email: your-email@example.com
description: >- 
  Data portfolio showcasing analytics, visualizations, and impact-driven dashboards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://korwa.github.io" # the base hostname & protocol

theme: minimal-mistakes-jekyll

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

plugins:
  - jekyll-remote-theme
