title: "Susan Korwa | Impact Data Analyst"
email: susankorwa7@gmail.com
description: >-
  Portfolio of Susan Korwa — Impact Systems Officer and MEAL Analyst.
  Experienced in Power BI, R, SQL, Python, ODK, and QGIS.
baseurl: ""
url: "https://korwa.github.io"
markdown: kramdown

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

google_analytics: UA-000000-0

nav:
  - title: "Home"
    url: "/"
  - title: "Toolbox"
    url: "/toolbox/"
  - title: "Dashboards"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"
  - title: "Contact"
    url: "/contact/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
